# /config.toml

[logging]
  level = "INFO" # TRACE DEBUG INFO SUCCESS WARNING ERROR CRITICAL
  file_path = "logs/app.log"
  rotation = "10 MB"
  retention = "7 days"
  format = "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name}:{function}:{line} - {message}"
