# /config.toml

[logging]
  level = "DEBUG" # TRACE DEBUG INFO SUCCESS WARNING ERROR CRITICAL
  file_path = "logs/app.log"
  rotation = "10 MB"
  retention = "7 days"
  format = "{time:YYYY-MM-DD HH:mm:ss} | {level: <8} | {name: <10.10}:{function: <10.10}:{line: <4} | {message}"