[E1]
name = "Obtain x5 Dragon Defenders"
description = "Obtain x5 Dragon Defenders"
image = "place_holder.png"
color = "green"
points = 1

[E2]
name = "Obtain x5 Abyssal Whips"
description = "Obtain x5 Abyssal Whips"
image = "place_holder.png"
color = "green"
points = 1

[E3]
name = "Obtain an unsired"
description = "Obtain an unsired"
image = "place_holder.png"
color = "green"
points = 1

[E4]
name = "Any revenant ancient artefact"
description = "Any revenant ancient artefact"
image = "place_holder.png"
color = "green"
points = 1

[E5]
name = "Any wilderness weapon add on"
description = "(Claws of callisto, fangs of venenatis or skull of vet'ion)"
image = "place_holder.png"
color = "green"
points = 1

[E6]
name = "Obtain 1 dragon pickaxe from the wilderness"
description = "(Venenatis/Spindle, Vetion/Calvarion, Callisto/Artio, Chaos Elemental)"
image = "place_holder.png"
color = "green"
points = 1

[E7]
name = "One pair of araena boots"
description = "One pair of araena boots"
image = "place_holder.png"
color = "green"
points = 1

[E8]
name = "Any of the wilderness rings"
description = "(Tyrannical ring, treasonous ring or ring of the gods)"
image = "place_holder.png"
color = "green"
points = 1

[E9]
name = "Obtain a sarachnis cudgel"
description = "Obtain a sarachnis cudgel"
image = "place_holder.png"
color = "green"
points = 1

[E10]
name = "Any Zulrah unique"
description = "(Tanzanite fang, Magic Fang, Serpentine visage, Uncut onyx, Tanzanite mutagen, Magma Mutagen, Jar of Swamp or Pet Snakeling)"
image = "place_holder.png"
color = "green"
points = 1

[E11]
name = "Make a twinflame staff"
description = "(Fire element staff crown and a ice elemental staff crown)"
image = "place_holder.png"
color = "green"
points = 1

[E12]
name = "Any TOA Gem"
description = "(eye of the corruptor, jewel of the sun, breach of the scarab, jewel of amascut)"
image = "place_holder.png"
color = "green"
points = 1

[E13]
name = "Obtain a Dharok great axe"
description = "Obtain a Dharok great axe"
image = "place_holder.png"
color = "green"
points = 1

[E14]
name = "Obtain an Enhanced crystal teleport seed"
description = "Obtain an Enhanced crystal teleport seed"
image = "place_holder.png"
color = "green"
points = 1

[E15]
name = "Obtain a curved bone"
description = "Obtain a curved bone"
image = "place_holder.png"
color = "green"
points = 1

[E16]
name = "Obtain Sulphur blades AND Glacial temotli"
description = "Obtain Sulphur blades AND Glacial temotli"
image = "place_holder.png"
color = "green"
points = 1

[E17]
name = "Obtain a zenyte shard"
description = "Obtain a zenyte shard"
image = "place_holder.png"
color = "green"
points = 1

[E18]
name = "Obtain KBD heads"
description = "Obtain KBD heads"
image = "place_holder.png"
color = "green"
points = 1

[E19]
name = "Obtain a kraken tentacle OR a trident of the seas"
description = "Obtain a kraken tentacle OR a trident of the seas"
image = "place_holder.png"
color = "green"
points = 1

[E20]
name = "Obtain a fedora"
description = "Obtain a fedora"
image = "place_holder.png"
color = "green"
points = 1

[E21]
name = "Any GOTR dye"
description = "Any GOTR dye"
image = "place_holder.png"
color = "green"
points = 1

[E22]
name = "Farmer's Outfit"
description = "(400 Tithe farm points are required in total as a team)"
image = "place_holder.png"
color = "green"
points = 1

[E23]
name = "Obtain a berserker ring"
description = "Obtain a berserker ring"
image = "place_holder.png"
color = "green"
points = 1

[E24]
name = "ANY jar from a boss"
description = "ANY jar from a boss"
image = "place_holder.png"
color = "green"
points = 1

[M1]
name = "One Venator shard AND One Ancient icon"
description = "One Venator shard AND One Ancient icon"
image = "place_holder.png"
color = "yellow"
points = 2

[M2]
name = "All 3 cerberus crystals"
description = "(Primordial crystal, Pegasian crystal and Eternal crystal)"
image = "place_holder.png"
color = "yellow"
points = 2

[M3]
name = "One full set of mix matched barrows set"
description = "(Helmet slot, body slot, legs slot, weapon slot - each piece must be from a different barrows brother)"
image = "place_holder.png"
color = "yellow"
points = 2

[M4]
name = "Obtain an armadyl crossbow"
description = "Obtain an armadyl crossbow"
image = "place_holder.png"
color = "yellow"
points = 2

[M5]
name = "Obtain a basilisk jaw"
description = "Obtain a basilisk jaw"
image = "place_holder.png"
color = "yellow"
points = 2

[M6]
name = "Obtain an Osmumten's fang"
description = "Obtain an Osmumten's fang"
image = "place_holder.png"
color = "yellow"
points = 2

[M7]
name = "Obtain a pharaoh scepter"
description = "Obtain a pharaoh scepter"
image = "place_holder.png"
color = "yellow"
points = 2

[M8]
name = "1 mil Hunter xp as a team"
description = "1 mil Hunter xp as a team"
image = "place_holder.png"
color = "yellow"
points = 2

[M9]
name = "Either an Arcane prayer scroll OR a Dexterous prayer scroll"
description = "Either an Arcane prayer scroll OR a Dexterous prayer scroll"
image = "place_holder.png"
color = "yellow"
points = 2

[M10]
name = "Any Vorkath Unique"
description = "(Dragonbone necklace, Jar of decay, Draconic visage, Skeletal visage or Vorki pet)"
image = "place_holder.png"
color = "yellow"
points = 2

[M11]
name = "Complete a mismatched moons set"
description = "(Helmet slot, body slot, leg slot and weapon slot - participants may get ANY of the pieces as long as each slot is filled out)"
image = "place_holder.png"
color = "yellow"
points = 2

[M12]
name = "Either a Dragon hunter wand OR a Tome of Earth"
description = "Either a Dragon hunter wand OR a Tome of Earth"
image = "place_holder.png"
color = "yellow"
points = 2

[M13]
name = "Obtain a blood shard"
description = "Obtain a blood shard"
image = "place_holder.png"
color = "yellow"
points = 2

[M14]
name = "Obtain a crystal tool seed"
description = "Obtain a crystal tool seed"
image = "place_holder.png"
color = "yellow"
points = 2

[M15]
name = "Obtain 5 awakeners orbs"
description = "Obtain 5 awakeners orbs"
image = "place_holder.png"
color = "yellow"
points = 2

[M16]
name = "1 mil Woodcutting xp as a team"
description = "1 mil Woodcutting xp as a team"
image = "place_holder.png"
color = "yellow"
points = 2

[M17]
name = "Obtain an abyssal lantern"
description = "Obtain an abyssal lantern"
image = "place_holder.png"
color = "yellow"
points = 2

[M18]
name = "Obtain a bottomless compost bucket"
description = "Obtain a bottomless compost bucket"
image = "place_holder.png"
color = "yellow"
points = 2

[M19]
name = "Obtain a calcified acorn"
description = "(900 termites are required in total as a team)"
image = "place_holder.png"
color = "yellow"
points = 2

[M20]
name = "Obtain one tormented synapse and one set of burning claws"
description = "(1 tormented synapse and 2 burning claw drops are required to create a full set)"
image = "place_holder.png"
color = "yellow"
points = 2

[M21]
name = "Obtain the full pyromancers outfit"
description = "(This includes the pyromancer hood, pyromancer garb, pyromancer robe, and the pyromancer boots)"
image = "place_holder.png"
color = "yellow"
points = 2

[M22]
name = "Obtain either a Tome of water OR a Big harpoon fish"
description = "Obtain either a Tome of water OR a Big harpoon fish"
image = "place_holder.png"
color = "yellow"
points = 2

[M23]
name = "Obtain both of the wilderness shields"
description = "(The odium ward and the malediction ward)"
image = "place_holder.png"
color = "yellow"
points = 2

[M24]
name = "1 mil Thieving xp as a team"
description = "1 mil Thieving xp as a team"
image = "place_holder.png"
color = "yellow"
points = 2

[H1]
name = "Obtain any TWO Godwars dungeon hilts"
description = "(NO DUPES - Armadyl hilt, Bandos hilt, Saradomin hilt, Zamorak hilt)"
image = "place_holder.png"
color = "orange"
points = 3

[H2]
name = "Obtain a dragon warhammer"
description = "(YOU CAN use an alt to safe spot!)"
image = "place_holder.png"
color = "orange"
points = 3

[H3]
name = "Any piece of oathplate"
description = "(Oathplate helmet, Oathplate legs or Oathplate chest)"
image = "place_holder.png"
color = "orange"
points = 3

[H4]
name = "Obtain a nightmare unique"
description = "(Nightmare staff, Inquisitor's great helm, Inquisitor's hauberk, Inquisitor's plateskirt, Inquisitor's mace, Eldritch orb, Harmonised orb, Volatile orb, Jar of dreams or Little nightmare pet)"
image = "place_holder.png"
color = "orange"
points = 3

[H5]
name = "Complete a Noxious Halberd"
description = "(Due to dupe protection any 3 nox halberd pieces are required to count as a completion doesn't have to be 3 different ones)"
image = "place_holder.png"
color = "orange"
points = 3

[H6]
name = "Obtain a Ring of endurance"
description = "Obtain a Ring of endurance"
image = "place_holder.png"
color = "orange"
points = 3

[H7]
name = "Obtain a fortis colosseum unique"
description = "(Echo crystal, Sunfire fanatic helm, Sunfire fanatic cuirass, Sunfire fanatic chausses, Tonalztics of ralos, Uncut onyx, Pet Smol heredit - QUIVER DOES NOT COUNT AS A UNIQUE)"
image = "place_holder.png"
color = "orange"
points = 3

[H8]
name = "Complete a full voidwaker"
description = "Complete a full voidwaker"
image = "place_holder.png"
color = "orange"
points = 3

[H9]
name = "Obtain any wilderness weapon"
description = "(Craw's bow, Thammoran's sceptre or a Viggora's chainmace)"
image = "place_holder.png"
color = "orange"
points = 3

[H10]
name = "Obtain a Doom of Mokhaiotl unique"
description = "(Avernic Treads, Eye of ayak, Mokhaiotl Cloth or Pet Dom)"
image = "place_holder.png"
color = "orange"
points = 3

[H11]
name = "Complete a set of bandos"
description = "(bandos chestplate, bandos tassets and bandos boots)"
image = "place_holder.png"
color = "orange"
points = 3

[H12]
name = "Obtain a kit from Challenge mode COX OR Hardmode TOB"
description = "(Twisted ancestral kit OR Holy ornament kit OR sanguine ornament kit)"
image = "place_holder.png"
color = "orange"
points = 3

[H13]
name = "Obtain a Hydra claw OR a Hydra leather"
description = "Obtain a Hydra claw OR a Hydra leather"
image = "place_holder.png"
color = "orange"
points = 3

[H14]
name = "Obtain a Nex Unique"
description = "(Zaryte vambraces, Nihil horn, Torva full helm [d], Torva platebody [d], Torva platelegs [d], Ancient Hilt, Nexling pet)"
image = "place_holder.png"
color = "orange"
points = 3

[I1]
name = "Any two megarares"
description = "(Tumeken's Shadow, Twisted Bow, Scythe of vitur - DUPES ARE ALLOWED)"
image = "place_holder.png"
color = "red"
points = 5

[I2]
name = "A raid armour piece from each raid"
description = "(One armour piece from TOB, COX and TOA - you CAN get all three leg slots for example as long as they are from the 3 different raids)"
image = "place_holder.png"
color = "red"
points = 5

[I3]
name = "Any mutagen from Zulrah"
description = "(Tanzanite mutagen OR Magma Mutagen)"
image = "place_holder.png"
color = "red"
points = 5

[I4]
name = "Corporal beast unique"
description = "(Spectral sigil, Arcane sigil, Elysian sigil, Jar of Spirits, Pet dark core)"
image = "place_holder.png"
color = "red"
points = 5

[I5]
name = "Obtain a Metamorphic dust OR Sanguine dust"
description = "Obtain a Metamorphic dust OR Sanguine dust"
image = "place_holder.png"
color = "red"
points = 5

[I6]
name = "Obtain an Enhanced crystal weapon seed"
description = "Obtain an Enhanced crystal weapon seed"
image = "place_holder.png"
color = "red"
points = 5

[I7]
name = "Obtain full virtus"
description = "(Virtus mask, Vistus robe top and virtus robe bottoms)"
image = "place_holder.png"
color = "red"
points = 5

[I8]
name = "Build a soul reaper axe from scratch"
description = "(As a team you require Leviathan's lure, Siren's staff, Executioner's axe head and the Eye of duke)"
image = "place_holder.png"
color = "red"
points = 5

[C1]
name = "Alch your infernal cape"
description = "Alch your infernal cape on discord stream where an bingo mod is watching"
image = "place_holder.png"

[C2]
name = "Obtain either an imbued heart or an eternal gem"
description = "Obtain either an imbued heart or an eternal gem"
image = "place_holder.png"

[C3]
name = "Obtain ANY pet"
description = "(Ineligible pets: Pet chaos elemental, Chompy Chick, Skotos, Tzrek-jad, Jal-nib-rek, Smol Heredit, Yami though the contract of familiar acquisition)"
image = "place_holder.png"

[C4]
name = "Obtain 3rd age"
description = "Obtain 3rd age"
image = "place_holder.png"
